CREATE TABLE STUDENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100),
    ENROLLMENT VARCHAR (11) UNIQUE
);

CREATE TABLE BOOK (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
     TITLE VARCHAR (100),
     EDITOR VARCHAR (50),
	 STATUS VARCHAR (20)
);

CREATE TABLE LOAN (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
     CODIGO INTEGER,
     STUDENT_ID INTEGER REFERENCES STUDENT (ID),
     DATE_LOAN TIMESTAMP,
     STATUS VARCHAR (20),
     FOREIGN KEY (student_id) REFERENCES student(id)
);

CREATE TABLE ITEM_LOAN (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOAN_ID INTEGER REFERENCES LOAN (ID),
    BOOK_ID INTEGER REFERENCES BOOK (ID),
	FOREIGN KEY (loan_id) REFERENCES loan(id),
    FOREIGN KEY (book_id) REFERENCES book(id)
);

CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);